name: Rust create & push Documentation

on:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
    - uses: actions/checkout@v2
    - name: Create documentation
      run: cargo doc --document-private-items --no-deps -v
    - name: Copy docs to tmp
      shell: bash
      run: \cp -rf target/doc /tmp/docs

    - uses: actions/checkout@v2
      with:
        ref: gh-pages
    - name: Copy docs back to gh-pages
      shell: bash
      run: \cp -rf /tmp/docs .
    - name: Commit docs
      shell: bash
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Github Action Push Docs"
        git add --all
        git commit -m "Add docs from https://github.com/JakubKoralewski/mandelbrot-wgpu-rs/commit/$GITHUB_SHA" || echo "No changes to commit"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
